
export enum Responses {
	SUCCESS = "SUCCESS",
}

export enum AccountErrors {
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
	ACCOUNT_NOT_WHITELISTED = "ACCOUNT_NOT_WHITELISTED",
	ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
	ACCOUNT_ALREADY_CONNECTED = "ACCOUNT_ALREADY_CONNECTED",
}

export enum GenericCreationErrors {
	OBJECT_ALREADY_EXISTS = "OBJECT_ALREADY_EXISTS",
	CANNOT_CREATE_OBJECT = "CANNOT_CREATE_OBJECT",
	OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
}

export enum GenericErrors {

}
